"""Add created_year to artworks

Revision ID: 29eb5e4b5940
Revises: b281ad2620b7
Create Date: 2025-12-31 02:25:00.203549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eb5e4b5940'
down_revision: Union[str, Sequence[str], None] = 'b281ad2620b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('created_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'created_year')
    # ### end Alembic commands ###
